[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1E4488"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5FC"
textColor = "#020202"
font = "sans serif"
